# -*- coding: utf-8 -*-
"""similarity_loudness.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mjo4BERcx1tZgVD5-ummlnFi9kbTFd9N
"""

!pip install librosa

import librosa
import IPython.display
import matplotlib.pyplot as plt
import librosa.display
import numpy

from google.colab import drive
drive.mount('/content/drive')

ls

x, sr = librosa.load('/content/drive/My Drive/PAS/Marina/MS-1.WAV')

sr

x.shape

librosa.get_duration(x, sr)

#listen to signal
IPython.display.Audio(x, rate=sr)

#plot the signal
plt.figure()
plt.subplot(3, 1, 1)
librosa.display.waveplot(x, sr=sr)
plt.title('Marina 1')

hop_length = 256
frame_length = 512

energy = numpy.array([
    sum(abs(x[i:i+frame_length]**2))
    for i in range(0, len(x), hop_length)
])

energy.shape

rmse = librosa.feature.rmse(x, frame_length=frame_length, hop_length=hop_length, center=True)

rmse.shape

rmse = rmse[0]

frames = range(len(energy))
t = librosa.frames_to_time(frames, sr=sr, hop_length=hop_length)

plt.plot(x,normalize(rmse), color='r')

y, sr = librosa.load('/content/drive/My Drive/PAS/Marina/MS-1.WAV')
librosa.feature.rms(y=y)

S, phase = librosa.magphase(librosa.stft(y))
rms = librosa.feature.rms(S=S)

plt.figure()
plt.subplot(2, 1, 1)
plt.semilogy(rms.T, label='RMS Energy')
plt.xticks([])
plt.xlim([0, rms.shape[-1]])
plt.legend(loc='best')
plt.subplot(2, 1, 2)
librosa.display.specshow(librosa.amplitude_to_db(S, ref=numpy.max),y_axis='log', x_axis='time')
plt.title('log Power spectrogram')
plt.tight_layout()

IPython.display.Audio(y, rate=sr)

y, sr = librosa.load('/content/drive/My Drive/PAS/Maryam/SF-1.WAV')
librosa.feature.rms(y=y)

S, phase = librosa.magphase(librosa.stft(y))
rms = librosa.feature.rms(S=S)

plt.figure()
plt.subplot(2, 1, 1)
plt.semilogy(rms.T, label='RMS Energy')
plt.xticks([])
plt.xlim([0, rms.shape[-1]])
plt.legend(loc='best')
plt.subplot(2, 1, 2)
librosa.display.specshow(librosa.amplitude_to_db(S, ref=numpy.max),y_axis='log', x_axis='time')
plt.title('log Power spectrogram')
plt.tight_layout()

y, sr = librosa.load('/content/drive/My Drive/PAS/Sami/SM-1.WAV')
librosa.feature.rms(y=y)

S, phase = librosa.magphase(librosa.stft(y))
rms = librosa.feature.rms(S=S)

plt.figure()
plt.subplot(2, 1, 1)
plt.semilogy(rms.T, label='RMS Energy')
plt.xticks([])
plt.xlim([0, rms.shape[-1]])
plt.legend(loc='best')
plt.subplot(2, 1, 2)
librosa.display.specshow(librosa.amplitude_to_db(S, ref=numpy.max),y_axis='log', x_axis='time')
plt.title('log Power spectrogram')
plt.tight_layout()

IPython.display.Audio(y, rate=sr)

y, sr = librosa.load('/content/drive/My Drive/PAS/results/MS-1__10000_0.231(17)/(10000).wav')
librosa.feature.rms(y=y)

S, phase = librosa.magphase(librosa.stft(y))
rms = librosa.feature.rms(S=S)

plt.figure()
plt.subplot(2, 1, 1)
plt.semilogy(rms.T, label='RMS Energy')
plt.xticks([])
plt.xlim([0, rms.shape[-1]])
plt.legend(loc='best')
plt.subplot(2, 1, 2)
librosa.display.specshow(librosa.amplitude_to_db(S, ref=numpy.max),y_axis='log', x_axis='time')
plt.title('log Power spectrogram')
plt.tight_layout()

y, sr = librosa.load('/content/drive/My Drive/PAS/Maryam/SF-17.WAV')
librosa.feature.rms(y=y)

S, phase = librosa.magphase(librosa.stft(y))
rms = librosa.feature.rms(S=S)

plt.figure()
plt.subplot(2, 1, 1)
plt.semilogy(rms.T, label='RMS Energy')
plt.xticks([])
plt.xlim([0, rms.shape[-1]])
plt.legend(loc='best')
plt.subplot(2, 1, 2)
librosa.display.specshow(librosa.amplitude_to_db(S, ref=numpy.max),y_axis='log', x_axis='time')
plt.title('log Power spectrogram')
plt.tight_layout()

y, sr = librosa.load('/content/drive/My Drive/PAS/Marina/MS-17.WAV')
librosa.feature.rms(y=y)

S, phase = librosa.magphase(librosa.stft(y))
rms = librosa.feature.rms(S=S)

plt.figure()
plt.subplot(2, 1, 1)
plt.semilogy(rms.T, label='RMS Energy')
plt.xticks([])
plt.xlim([0, rms.shape[-1]])
plt.legend(loc='best')
plt.subplot(2, 1, 2)
librosa.display.specshow(librosa.amplitude_to_db(S, ref=numpy.max),y_axis='log', x_axis='time')
plt.title('log Power spectrogram')
plt.tight_layout()

y, sr = librosa.load('/content/drive/My Drive/PAS/Maryam/SF-1.WAV')
librosa.feature.rms(y=y)

S, phase = librosa.magphase(librosa.stft(y))
rms = librosa.feature.rms(S=S)

plt.figure()
plt.subplot(2, 1, 1)
plt.semilogy(rms.T, label='RMS Energy')
plt.xticks([])
plt.xlim([0, rms.shape[-1]])
plt.legend(loc='best')
plt.subplot(2, 1, 2)
librosa.display.specshow(librosa.amplitude_to_db(S, ref=numpy.max),y_axis='log', x_axis='time')
plt.title('log Power spectrogram')
plt.tight_layout()

y, sr = librosa.load('/content/drive/My Drive/PAS/Maryam/SF-15.WAV')
librosa.feature.rms(y=y)

S, phase = librosa.magphase(librosa.stft(y))
rms = librosa.feature.rms(S=S)

plt.figure()
plt.subplot(2, 1, 1)
plt.semilogy(rms.T, label='RMS Energy')
plt.xticks([])
plt.xlim([0, rms.shape[-1]])
plt.legend(loc='best')
plt.subplot(2, 1, 2)
librosa.display.specshow(librosa.amplitude_to_db(S, ref=numpy.max),y_axis='log', x_axis='time')
plt.title('log Power spectrogram - SF-15')
plt.tight_layout()

IPython.display.Audio(y, rate=sr)

y, sr = librosa.load('/content/drive/My Drive/PAS/Marina/MS-27.WAV')
librosa.feature.rms(y=y)

S, phase = librosa.magphase(librosa.stft(y))
rms = librosa.feature.rms(S=S)

plt.figure()
plt.subplot(2, 1, 1)
plt.semilogy(rms.T, label='RMS Energy')
plt.xticks([])
plt.xlim([0, rms.shape[-1]])
plt.legend(loc='best')
plt.subplot(2, 1, 2)
librosa.display.specshow(librosa.amplitude_to_db(S, ref=numpy.max),y_axis='log', x_axis='time')
plt.title('log Power spectrogram- MS-27')
plt.tight_layout()

y, sr = librosa.load('/content/drive/My Drive/PAS/Maryam/SF-27.WAV')
librosa.feature.rms(y=y)

S, phase = librosa.magphase(librosa.stft(y))
rms = librosa.feature.rms(S=S)

plt.figure()
plt.subplot(2, 1, 1)
plt.semilogy(rms.T, label='RMS Energy')
plt.xticks([])
plt.xlim([0, rms.shape[-1]])
plt.legend(loc='best')
plt.subplot(2, 1, 2)
librosa.display.specshow(librosa.amplitude_to_db(S, ref=numpy.max),y_axis='log', x_axis='time')
plt.title('log Power spectrogram - SF-27')
plt.tight_layout()

y, sr = librosa.load('/content/drive/My Drive/PAS/results/MS-27_SF-15_10000_0.02/(10000).wav')
librosa.feature.rms(y=y)

S, phase = librosa.magphase(librosa.stft(y))
rms = librosa.feature.rms(S=S)

plt.figure()
plt.subplot(2, 1, 1)
plt.semilogy(rms.T, label='RMS Energy')
plt.xticks([])
plt.xlim([0, rms.shape[-1]])
plt.legend(loc='best')
plt.subplot(2, 1, 2)
librosa.display.specshow(librosa.amplitude_to_db(S, ref=numpy.max),y_axis='log', x_axis='time')
plt.title('log Power spectrogram- MS-27_SF-15')
plt.tight_layout()

y, sr = librosa.load('/content/drive/My Drive/PAS/Sami/SM-1.WAV')
librosa.feature.rms(y=y)

S, phase = librosa.magphase(librosa.stft(y))
rms = librosa.feature.rms(S=S)

plt.figure()
plt.subplot(2, 1, 1)
plt.semilogy(rms.T, label='RMS Energy')
plt.xticks([])
plt.xlim([0, rms.shape[-1]])
plt.legend(loc='best')
plt.subplot(2, 1, 2)
librosa.display.specshow(librosa.amplitude_to_db(S, ref=numpy.max),y_axis='log', x_axis='time')
plt.title('log Power spectrogram')
plt.tight_layout()